### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by BnqDzj** [54ayao/Chinajsdelivr#18]
![image](https://github.com/54ayao/Chinajsdelivr/assets/64721413/f630d40e-a46a-4f37-bd2c-c777e190cb85)

**Comment by 54ayao** [comment]
您好 感谢您的反馈，关于您反馈的502 Bad Gateway 我们目前已完成修复，其原因测试的时候修改了上游dns，测试完成没改过来导致出错了，CDN去访问DCDN资源导致无法回源然后产生了502错误 目前已完成修复，再次感谢您的反馈

————————————————————————————————————————————————————————
Hello Thank you for your feedback, about your feedback 502 Bad Gateway We have completed the fix, the reason is that the upstream DNS was modified during the test, the test was completed and the error was not changed, and the CDN went to access the DCDN resource and could not return to the source and then generated a 502 error The fix has been completed, thank you again for your feedback

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/Chinajsdelivr/assets/86733666/2b00fbe0-8942-427d-a609-cc7394e83a3b)
测试图片
可以看到42个节点现在都已经是200了
